# https://golangci-lint.run/usage/configuration/

run:
  timeout: 3m

linters-settings:
  custom:
    tfproviderlint:
      path: ./bin/tfproviderlint-plugin.so
      description: "Terraform Provider Lint Tool"
      original-url: https://github.com/bflad/tfproviderlint
  errcheck:
    exclude: errcheck_excludes.txt

linters:
  enable:
    - gofmt
    - govet
    - tfproviderlint
