# GitHub Action reference: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: issue-opened

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  add-labels:
    runs-on: ubuntu-latest
    # This job contains steps which are expected to fail.
    continue-on-error: true
    steps:
      - name: Is opened by a collaborator?
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/collaborators/${{ github.event.sender.login }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Only add triage labels if they are NOT a collaborator.
      # This prevents the needs-triage label from being added.
      - uses: actions/checkout@v3
        if: ${{ failure() }}
      - uses: github/issue-labeler@v2.5
        if: ${{ failure() }}
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler-issue-triage.yml
          enable-versioned-regex: 0
