# This workflow runs acceptance tests on pull requests (CE)

name: pr-acceptance-ce

on:
  pull_request:
    # Acceptance tests are unnecessary to run on some types of PRs.
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  go-version:
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.go-version.outputs.go-version }}
    steps:
      - uses: actions/checkout@v3
      # Read the .go-version file and output it for other jobs to use.
      - id: go-version
        run: echo "::set-output name=go-version::$(cat .go-version)"

  acceptance-ce:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: [go-version]
    strategy:
      fail-fast: false
      matrix:
        gitlab-version: ["14.10.4-ce.0", "15.0.3-ce.0", "15.1.0-ce.0"]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ needs.go-version.outputs.go-version }}
      - uses: actions/checkout@v3
      # Cache the Go modules.
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ github.job }}-${{ runner.os }}-go${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum', 'GNUMakefile') }}
      - run: make testacc-up GITLAB_CE_VERSION=${{ matrix.gitlab-version }}
      - run: make testacc