# GitHub Action reference: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
# Enforce label requirements on pull requests, to prevent accidental merging.

name: pr-required-labels

on:
  pull_request_target:
    types: [opened, reopened, labeled, unlabeled]

permissions:
  pull-requests: read

jobs:
  required-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check do-not-merge
        uses: mheap/github-action-required-labels@v2
        with:
          mode: exactly
          count: 0
          labels: do-not-merge
      - name: Check needs-rebase
        uses: mheap/github-action-required-labels@v2
        with:
          mode: exactly
          count: 0
          labels: needs-rebase
